# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('semestre', models.IntegerField(default=1, verbose_name='Semestre de Ingresso')),
                ('ano', models.IntegerField(verbose_name='Ano de Ingresso')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100, verbose_name='Disciplina')),
                ('semestre', models.IntegerField(default=1, verbose_name='Semestre de Ingresso')),
                ('ano', models.IntegerField(default=2017, verbose_name='Ano de Ingresso')),
                ('alunos', models.ManyToManyField(to='api.Aluno')),
            ],
        ),
    ]
