# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('semestre', models.IntegerField(choices=[(1, 'Primeiro'), (2, 'Segundo')], default=1, verbose_name='Semestre')),
                ('ano', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2017, verbose_name='Ano')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=100, verbose_name='Disciplina')),
                ('semestre', models.IntegerField(choices=[(1, 'Primeiro'), (2, 'Segundo')], default=1, verbose_name='Semestre')),
                ('ano', models.IntegerField(choices=[(2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020)], default=2017, verbose_name='Ano')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('alunos', models.ManyToManyField(blank=True, to='api.Aluno', verbose_name='Alunos')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='turmas',
            field=models.ManyToManyField(blank=True, to='api.Turma', verbose_name='Turmas'),
        ),
    ]
